"""add_banner_phone_hours_online_to_pages

Revision ID: 63f57ccdc211
Revises: 7cdc933b7e85
Create Date: 2026-03-15 15:41:28.615685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63f57ccdc211'
down_revision: Union[str, None] = '7cdc933b7e85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_pages', sa.Column('banner_image_url', sa.String(length=500), nullable=True))
    op.add_column('business_pages', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('business_pages', sa.Column('business_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('business_pages', sa.Column('is_online_only', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_pages', 'is_online_only')
    op.drop_column('business_pages', 'business_hours')
    op.drop_column('business_pages', 'phone_number')
    op.drop_column('business_pages', 'banner_image_url')
    # ### end Alembic commands ###
