"""Add layout_config to business_pages

Revision ID: 85cb85a750af
Revises: c25c995b1c4e
Create Date: 2026-05-07 17:48:42.924409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85cb85a750af'
down_revision: Union[str, None] = 'c25c995b1c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_pages', sa.Column('layout_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_pages', 'layout_config')
    # ### end Alembic commands ###
